sudo: false
language: java
install:
- mvn -s .settings.xml install -q -U -DskipTests=true -Dmaven.test.redirectTestOutputToFile=true
script:
- mvn -s .settings.xml $MVN_GOAL -nsu -Dmaven.test.redirectTestOutputToFile=true
jdk:
- oraclejdk8
env:
  global:
  - FEATURE_BRANCH=$(echo ${TRAVIS_BRANCH} | grep "^.*/.*$" && echo true || echo false)
  - INTERNAL_BUILD=$(echo ${TRAVIS_REPO_SLUG} | grep -q "^SMARTRACTECHNOLOGY/.*$"
    && echo true || echo false)
  - MVN_GOAL=$([ "${TRAVIS_PULL_REQUEST}" == "false" -a "${TRAVIS_TAG}" == "" -a "${FEATURE_BRANCH}"
    == "false" -a "${INTERNAL_BUILD}" == "true" ] && echo deploy || echo install)
  - VERSION=$(mvn validate | grep Building | head -1 | sed -e 's/.* //')
  - secure: 1IyUE3QWEgLb9K9PRsVfM57H/y6w5mhmLkkbP2y+g2Izjc/J8RcuKiHLw1WFCpAkakZKov27dqkGvLlpYuzZ3CD/JpcdzS47q0euowaHcUcIgj9xelHiesz54oT/9uh4iNIYyLG1K/jQIc0rX5ZpJDs1lw0UcFy4N97M2q3TnUH/0oyO7aa/Fsmi0PbAOxwHujYUgjhJZ+DD9hWFFNraM9tBlxcmwqmjv4bGrw/0cEty3wMqDIN8nRs2vbAslsFGZvkNQD3rAhA+SkRMpjdo+EtjYEuL1MvuOLIzzdCDLABLirvzKlvPjXpe/m5Fpjq38w3SwD0G+SW1uuS365vrMFSGsABRs4sWDHTNgQmj/DyEb7bocPAeduF/moRXXi/OiXmZyiE+9pxny1uA8X4d+VKcjZmKG1VPIXxopUiYO82n26opTcDYBN+f29Qra84s+XNVJWiaODFIayGxK/E6gZfXyhh7CTiPR1mRRHbSY4kq2Letbc9Ak9GC1OuJkUG12BkL7VwPMmR7IwdRiGHuEqnw5pYDWAvlh+2WAXgn7YFKAoLtBvKD0RS7Hg3b8/dpzRek9S7L4zQEhitaolOccxVBts5ukxlPTIBjOGZpnUnnFyLtuFJlpD7nKHV7Vy9CUjiLjUuL17G4wd95++HNhbtS1+Zfre6zYYlQUb3v31A=
  - secure: PlETFfu8qQdBOQaYTHDs0jK3JkRe5v2LD7cjwNqvt0Jp7HcEYEEMOHAfoadHq0Hyjg3P4T5AYdLntcpWjtu5V+TzcrzcHMvF//pwIlVTELGncWdQsDKaVGQ0fX8qPr+16iamkCOGeayAnm4G6ezBG0nPLJnuRYf+pvUxh/RgYmwEdw/XRKXIOjhnSO7112SG6OP3FB/0ljMSlZXcZivJAnzCqp/WtaPmwFTHvl1O5V9lolgj59gUb2gPNhZdI5DMdT87tbGHeVPlNv6thPaMXA6sHmLxv9tOfAHovTbTPbCkcyH9yJQ6tQluHjHaoHMpqvYsUiAwpqBJiGgxanbVtMN2P6tHutd+KSVTfBp7hdJwjwJeCNWRQmLdq5zafs2yHr+fR+XJMIKxhm4bpqdWRr23Cbod2SPGjPmHHPpIYxJuIR6WecNpFpcuCKmEZMs5a+iKoqj6ad3naW1aY6f2W6LSC9/gkVcyeEhpqFb/LP29Cnf+dM7pBn3VoJSr+YldAAyfTsAW0GsDEcCjVz7jemelBvQxKu/sC1GiBsUQLlt0+ka6/C4oo0bbsQ5BR5AvjD3hRTmObVIM+UYkHlrhaP+Tr9wzOtYLMjTy6Jy7xfLCRfFZg34vhuSzw1fpdICWitqj9bThCKfmtEPNTYgKsjgxzrd1CEYWrWDFYu5QrfE=
notifications:
  slack:
    on_success: change
    rooms:
      secure: A0aPf18ViSkVq8jz8kcPXDFNIa+xaQSaglb8wTBJkYmj+v4KnolDhfuye5Mc/G1lMdT947ETW0ItOha+GdZ194tMEzfoMOaIAs+v6rTO/qKZH2YCKgJTuVjyEBj5rn9v1pLuZ7awMwO9UxfF8R/LQeq/ZhYrtdvuhQdx2EeDCFRLaceuIUyAtXtLF6vNd2PdXxNYYczL6teH+Y0aaxmkZ8cD1wzo5YOLTS4rOWcAcfxigKaTP+EKB6V8G/8gUapyMkxKE6KtRavwW7azifDUA6UuOxVHWef2BAhWYrvzbfj/212UU91mbozYtF4Un+uIzKOiD75MldqGmbpw3v+kAkFoJmtiho2CC3wmIXKtomAcxqjVjTMbf1+jd1a9HBcy3Jmrd7VIwJQMV/zWo+ukAot58K+QXdjLIEwwP9EQ/6PSDB/lUYh4saZVWQ5uiY33lT6bhWBxNNZjRyC+wLuRN8iEFHytE/fJddABnXtAbljKn/92Jml4i52GXHYm6DgUcIpx5o/7b0aC75SVpEbyTNFGQCHpZ37vqzfwcRa7MEZi6e2yheSVhjIXHvWc7lHU30lZBpT24s3PibM+E18Gi+TC2osOvGwpcDiEgd4NGrdGjEf58p5AEW5NLWwUtcYb4MD06IPJZJLkODF/bOOHAQWG3XjdZ0whIF3LWFRnJK4=
